export const dummyLeads = [
  {
    id: 1,
    name: "John Smith",
    email: "john@example.com",
    phone: "+971 50 123 4567",
    status: "Meeting Booked",
    interest: "Off-plan",
    budget: "$500,000 - $750,000",
    location: "Dubai Marina",
    nationality: "UK",
    gender: "Male",
    callRating: 5,
    notes: "Looking for 2BR apartment, ready to move within 6 months",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+1 212 555 1234",
    status: "Qualified",
    interest: "Secondary",
    budget: "$1,000,000 - $1,500,000",
    location: "Downtown Manhattan",
    nationality: "USA",
    gender: "Female",
    callRating: 4,
    notes: "Interested in a penthouse with city views",
  },
  {
    id: 3,
    name: "Peter Jones",
    email: "peter.jones@example.com",
    phone: "+44 20 7123 4567",
    status: "Not Interested",
    interest: "Off-plan",
    budget: "$250,000 - $500,000",
    location: "Canary Wharf",
    nationality: "UK",
    gender: "Male",
    callRating: 2,
    notes: "Budget too low for available properties",
  },
  {
    id: 4,
    name: "Sarah Williams",
    email: "sarah.williams@example.com",
    phone: "+61 2 9999 8888",
    status: "Follow Up",
    interest: "Secondary",
    budget: "$750,000 - $1,000,000",
    location: "Sydney CBD",
    nationality: "Australia",
    gender: "Female",
    callRating: 3,
    notes: "Needs more information on financing options",
  },
  {
    id: 5,
    name: "David Brown",
    email: "david.brown@example.com",
    phone: "+1 415 555 9999",
    status: "Meeting Scheduled",
    interest: "Off-plan",
    budget: "$500,000 - $750,000",
    location: "San Francisco",
    nationality: "USA",
    gender: "Male",
    callRating: 5,
    notes: "Looking for a 3BR house with a garden",
  },
]

export const dummyCallStats = {
  totalCalls: 486,
  callsReceived: 324,
  callsMade: 486,
  answered: 312,
  notAnswered: 174,
  notInterested: 89,
  callbacks: 156,
  meetingsBooked: 86,
  offplanInterest: 52,
  secondaryInterest: 34,
  avgDuration: "8:45",
  avgCostPerMeeting: 125,
  conversionRate: 0.25,
  meetingCount: 30,
  followUps: 15,
}

export const dummyCallHistory = [
  { date: "Mon", calls: 65, meetings: 12 },
  { date: "Tue", calls: 72, meetings: 15 },
  { date: "Wed", calls: 85, meetings: 18 },
  { date: "Thu", calls: 93, meetings: 22 },
  { date: "Fri", calls: 75, meetings: 19 },
  { date: "Sat", calls: 55, meetings: 10 },
  { date: "Sun", calls: 45, meetings: 8 },
]

