-- Insert test outbound calls
INSERT INTO calls (
    call_id,
    call_type,
    status,
    start_time,
    end_time,
    duration,
    customer_phone,
    customer_name,
    agent_id,
    recording_url,
    property_interest,
    lead_status,
    rating,
    notes
) VALUES 
(
    'test-call-001',
    'outbound',
    'ended',
    NOW() - interval '1 hour',
    NOW() - interval '45 minutes',
    900,
    '+44123456789',
    'John Smith',
    'agent-001',
    'https://example.com/recording-001.mp3',
    'Off-plan',
    'interested',
    4,
    'Customer interested in Dubai Marina properties'
),
(
    'test-call-002',
    'outbound',
    'ended',
    NOW() - interval '2 hours',
    NOW() - interval '1 hour 45 minutes',
    1200,
    '+44987654321',
    'Sarah Johnson',
    'agent-001',
    'https://example.com/recording-002.mp3',
    'Secondary',
    'very-interested',
    5,
    'Looking for immediate purchase in Downtown'
),
(
    'test-call-003',
    'outbound',
    'started',
    NOW(),
    NULL,
    NULL,
    '+44555666777',
    'Michael Brown',
    'agent-001',
    NULL,
    NULL,
    'new',
    NULL,
    'Ongoing call'
); 