-- Insert test data for leads
INSERT INTO leads (
    crm_id,
    name,
    phone,
    email,
    gender,
    location,
    property_interest,
    investment_type,
    budget_range,
    preferred_areas,
    status,
    priority,
    rating,
    ai_sentiment,
    ai_notes,
    source,
    notes
) VALUES
(
    'CRM-IN-2024-0001',
    'Ahmed Khan',
    '+971501234567',
    'ahmed.khan@email.com',
    'Male',
    'Dubai',
    'Off-plan',
    'Investment',
    '2M-5M AED',
    ARRAY['Dubai Marina', 'Palm Jumeirah'],
    'Interested',
    'High',
    5,
    0.92,
    'Strong interest in luxury properties. Ready to invest immediately.',
    'Website Form',
    'Looking for 3BR apartment with full marina view'
),
(
    'CRM-IN-2024-0002',
    'Sarah Wilson',
    '+971502345678',
    'sarah.w@email.com',
    'Female',
    'Abu Dhabi',
    'Secondary',
    'Personal Use',
    '1M-2M AED',
    ARRAY['Downtown Dubai', 'Business Bay'],
    'Follow-up',
    'High',
    4,
    0.85,
    'Interested in ready properties. Needs to move within 3 months.',
    'Phone Inquiry',
    'Requires modern finishing, prefers high floor'
),
(
    'CRM-OUT-2024-0001',
    'Mohammed Ali',
    '+971503456789',
    'mali@email.com',
    'Male',
    'Sharjah',
    'Both',
    'Investment',
    '1M-3M AED',
    ARRAY['JVC', 'JVT', 'Dubai Hills'],
    'New',
    'Medium',
    3,
    0.75,
    'Considering both off-plan and ready properties for investment.',
    'Property Portal',
    'Currently comparing different payment plans'
); 