-- Insert Not Interested leads
INSERT INTO leads (
    crm_id,
    name,
    phone,
    email,
    gender,
    location,
    property_interest,
    investment_type,
    budget_range,
    preferred_areas,
    status,
    priority,
    rating,
    ai_sentiment,
    ai_notes,
    source,
    notes
) VALUES
(
    'CRM-NI-2024-0001',
    'Fatima Hassan',
    '+971506789012',
    'fatima.h@email.com',
    'Female',
    'Dubai',
    'Off-plan',
    'Investment',
    '2M-4M AED',
    ARRAY['Dubai Marina'],
    'Not Interested',
    'Low',
    2,
    0.35,
    'Current prices above expected range. May reconsider in 6 months.',
    'Property Portal',
    'Found better options in Abu Dhabi'
),
(
    'CRM-NI-2024-0002',
    'John Miller',
    '+971507890123',
    'john.m@email.com',
    'Male',
    'Dubai',
    'Secondary',
    'Personal Use',
    '1M-2M AED',
    ARRAY['JVC', 'Sports City'],
    'Not Interested',
    'Low',
    1,
    0.25,
    'Location preferences not matching available properties.',
    'Website Form',
    'Looking for different area, budget constraints'
); 