-- Insert more test data with different statuses
INSERT INTO leads (
    crm_id,
    name,
    phone,
    email,
    gender,
    location,
    property_interest,
    investment_type,
    budget_range,
    preferred_areas,
    status,
    priority,
    rating,
    ai_sentiment,
    ai_notes,
    source,
    notes
) VALUES
-- Not Interested Leads
(
    'CRM-NI-2024-0001',
    'Fatima Hassan',
    '+971506789012',
    'fatima.h@email.com',
    'Female',
    'Dubai',
    'Off-plan',
    'Investment',
    '2M-4M AED',
    ARRAY['Dubai Marina'],
    'Not Interested',
    'Low',
    2,
    0.35,
    'Current prices above expected range. May reconsider in 6 months.',
    'Property Portal',
    'Found better options in Abu Dhabi'
),
(
    'CRM-NI-2024-0002',
    'John Miller',
    '+971507890123',
    'john.m@email.com',
    'Male',
    'Dubai',
    'Secondary',
    'Personal Use',
    '1M-2M AED',
    ARRAY['JVC', 'Sports City'],
    'Not Interested',
    'Low',
    1,
    0.25,
    'Location preferences not matching available properties.',
    'Website Form',
    'Looking for different area, budget constraints'
),

-- Callback Leads
(
    'CRM-CB-2024-0001',
    'Priya Sharma',
    '+971508901234',
    'priya.s@email.com',
    'Female',
    'Dubai',
    'Off-plan',
    'Investment',
    '3M-5M AED',
    ARRAY['Palm Jumeirah', 'Dubai Marina'],
    'Callback',
    'High',
    4,
    0.85,
    'Highly interested in luxury properties, requested evening callback.',
    'Property Portal',
    'Prefers callback after 6 PM GST'
),
(
    'CRM-CB-2024-0002',
    'Ali Mohammed',
    '+971509012345',
    'ali.m@email.com',
    'Male',
    'Abu Dhabi',
    'Secondary',
    'Personal Use',
    '2M-3M AED',
    ARRAY['Downtown Dubai'],
    'Callback',
    'Medium',
    3,
    0.70,
    'Interested in viewing properties next weekend.',
    'Website Chat',
    'Schedule callback for property viewing arrangement'
),

-- No Answer Leads
(
    'CRM-NA-2024-0001',
    'Robert Chen',
    '+971507890123',
    'robert.c@email.com',
    'Male',
    'Dubai',
    'Secondary',
    'Personal Use',
    '3M-5M AED',
    ARRAY['Emirates Hills', 'Arabian Ranches'],
    'No Answer',
    'Medium',
    0,
    0.0,
    'Multiple attempts made during different times of day.',
    'Email Inquiry',
    'Attempted contact 3 times - no response'
),
(
    'CRM-NA-2024-0002',
    'Maria Garcia',
    '+971509876543',
    'maria.g@email.com',
    'Female',
    'Dubai',
    'Off-plan',
    'Investment',
    '1M-2M AED',
    ARRAY['JVC', 'Dubai South'],
    'No Answer',
    'Low',
    0,
    0.0,
    'Two attempts made - morning and afternoon.',
    'Website Form',
    'Try reaching during evening hours'
),

-- Follow-up Leads
(
    'CRM-IN-2024-0003',
    'David Wilson',
    '+971501122334',
    'david.w@email.com',
    'Male',
    'Dubai',
    'Off-plan',
    'Investment',
    '5M-7M AED',
    ARRAY['Palm Jumeirah', 'Dubai Hills Estate'],
    'Follow-up',
    'High',
    4,
    0.88,
    'Very interested in luxury properties, requested detailed floor plans.',
    'Referral',
    'Send floor plans and payment schedule'
),
(
    'CRM-OUT-2024-0003',
    'Aisha Rahman',
    '+971502233445',
    'aisha.r@email.com',
    'Female',
    'Dubai',
    'Secondary',
    'Personal Use',
    '2M-3M AED',
    ARRAY['Dubai Marina', 'JBR'],
    'Follow-up',
    'Medium',
    3,
    0.72,
    'Interested in viewing multiple properties.',
    'Property Portal',
    'Schedule viewings for next week'
); 